### ISSUE TITLE
Broken slides link

### ISSUE THREAD

**Issue by maelle** [gadenbuie/slides#2]
https://slides.garrickadenbuie.com/extra-awesome-slides/intro/ is a broken link, found via https://www.garrickadenbuie.com/talk/trug-extra-awesome-xaringan/

**Comment by gadenbuie** [comment]
Oops, I recently moved that presentation from its own github pages backed site into this repo. The link should be https://slides.garrickadenbuie.com/extra-awesome-xaringan/docs/intro/ or I should move the files into the right spot and have the link be https://slides.garrickadenbuie.com/extra-awesome-xaringan/intro/
